name: Coding standard

on: [push, pull_request]

jobs:
    coding-standard:
        runs-on: ubuntu-latest

        name: Coding standard
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  coverage: none

            - run: composer install --no-progress --prefer-dist
            - run: bin/phpcs --colors --standard=PSR2 Parser/ Statement/ Tests/
